### ISSUE TITLE
Support for .NET Standard?

### ISSUE THREAD

**Issue by Leon99** [csnemes/tracer#51] opened 2017-07-07 11:32 UTC
Given that Fody now supports .NET Standard, how hard would it be for Tracer to support it as well?

**Comment by gautelo** [comment] 2017-07-08 10:37
Link? Tried searching for it. Only finding mentions of .NET Standard for Fody/PropertyChanged and Fody/Obsolete.

I imagine it will tricky to get a hold of the ILoggerFactory from the weaver, no? Or is that what the mentioned support is adding; a way for you to get things injected from the IoC container into the weavers?

In any case, I fully support this ticket, since it would be great if we could simply add a Tracer for Microsoft.Extensions.Logging, rather than a specific logger. That would effectively allow us to use Tracer for library projects as well, something which I consider difficult at the moment since it forces a dependency on a specific logger as it is.

**Comment by Leon99** [comment] 2017-07-08 10:45
https://github.com/Fody/Fody/issues/206#issuecomment-296487890

> simply add a Tracer for Microsoft.Extensions.Logging
I'd say let's start by just enabling what tracer can do now for .NET Standard/.NET Core.

Here's an example: https://github.com/Fody/Fody/issues/324#issuecomment-298276824

**Comment by gautelo** [comment] 2017-07-08 13:17
Well, then I'm not sure how you want to achieve this for Tracer. Cause, like I said, you need access to the ILoggerFactory from the weaver somehow.

Thinking about it, I guess one might add an extension method for ms.extensions.di which adds the ILoggerFactory to a static class used by the Tracer weaver or something like that. Feels a bit hacky, but it's probably the best that may be done.

**Comment by csnemes** [comment] 2017-07-08 14:03
Actually the rewriter (Tracer) depends neither on the adapter nor on the logger itself. It assumes that a class will be present with the given name in the given namespace having the required methods. Moving an adapter to .net standard only requires that the logger is on .net standard as the adapter references it. So for each existing adapter I'll check if the logger has already moved under .net standard and if so I can update the adapter. As Leon99 said for Microsoft.Extensions.Logging just a new Tracer.Adapter is needed. I'll take a look on this logger to see what it can offer. A slightly different issue is to move the rewriter (Tracer itself) to .net standard so you can include and use it on different platforms. That requires the core Fody (and Cecil) to work on .net standard as well. I also check to see what is the current status with Fody.

**Comment by gautelo** [comment] 2017-07-08 16:29
I was more thinking of the static logger feature. Wouldn't that have to be instantiated from the ILoggerFactory?

**Comment by Leon99** [comment] 2017-07-09 10:08
> A slightly different issue is to move the rewriter (Tracer itself) to .net standard so you can include and use it on different platforms. 
That is precisely what this issue is about.

> That requires the core Fody (and Cecil) to work on .net standard as well. I also check to see what is the current status with Fody.
It's all good and ready (see the links I mentioned).

**Comment by gautelo** [comment] 2017-07-09 12:05
Oh, I completely missed the point then. My bad. Thought you wanted a Microsoft.Extensions.Logging Tracer implementation. Cause that would be neat.

**Comment by csnemes** [comment] 2017-07-10 15:08
I plan to do both, because that makes the most sense; being able to use Tracer on .NET Core and .NET 4.x. plus having an adapter to the MS Logging as it can be used on both platforms. I'll let you know how I progress with these,

**Comment by AlexPalma72** [comment] 2017-07-17 08:58
@csnemes, well looks like something on Tracer points to the assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
I have my own tracer adapter that uses nlog, I updated nlog to use version 5.0.0-beta09, since this is the one that supports .netstandard and ASP.NETCore.
all my logging definition the stating Log, attributes and the Adapter are on their own project, I then reference that project. so all solution builds fine the Tracer add the log calls to the compiled dlls,
I then have an ASP.NET CORE project that I configured with Nlog using what is shown <a href="https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-(csproj---vs2017)">here</a> but as soon as run the Asp.net project it bows up with the error 'Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.' 
if I remove all references to my loging project and just leave the Nlog on the ASP.NET CORE  and remove tracer from related projects all works fine.
any ideas?

**Comment by csnemes** [comment] 2017-07-19 07:55
I think the whole thing works only when you property target .net standard, but I'm not sure. Anyway I've started the porting to .net standard so I hope it will solve this problem.

**Comment by AlexPalma72** [comment] 2017-07-19 09:03
Great, 
I think the prb is on the Tracer assembly, I have my own tracer class and attributes all defined in a .net standard 1.3 project that project that references Fody and Tracer.Fody, all build fine but when launching the app I don't even get into the static main method it fails right away, that's why I'm saying that must be Tracer that uses the System.dll instead of System.Core.dll when changing the IL, and would make sense since Tracer is not a .net standard project.
so hopefully with your port to .net standard then all should work.

**Comment by csnemes** [comment] 2017-08-04 15:28
I just wanted to let you know that the porting will take more time than expected. I've ran into the issue of properly resolving dependencies when referencing netstandard libraries. I've managed to create the nestandard version of the log4net add-in using the netstandard version of log4net. But when I'm trying to use the adapter in a classic (e.g. 4.6.1) project it fails during runtime by not finding the references needed for log4net (netstandard version). This can be reproduced even without any weaving so it is not a Fody specific problem. I think this scenario (using netstandard from 4.6.1) is pretty common and must be supported, I consider this issue as a showstopper for moving to netstandard. Anyway I'm trying to find some resolution to this problem, but I think (after working a bit with netstd) that netstandard and especially the tooling is still in its infancy.

**Comment by Leon99** [comment] 2017-08-04 23:47
According to https://github.com/dotnet/standard/blob/master/docs/netstandard-20/README.md, nestandard 2.0 should be binary compatible with 4.6.1. I haven't tried it yet though.

**Comment by csnemes** [comment] 2017-08-06 05:42
netstandard 2.0 is still preview. I tried to port it to netstandard 1.4 but ran into issues like:
https://github.com/Microsoft/msbuild/issues/1582
https://github.com/dotnet/standard/issues/282

**Comment by csnemes** [comment] 2017-08-15 08:10
As netstandard 2.0 and core 2.0 are final, I'll give a try.

**Comment by AlexPalma72** [comment] 2017-09-11 09:24
@csnemes hi, any new news about this?

**Comment by csnemes** [comment] 2017-09-12 07:50
Still struggling with it. I can now compile the weaver, run most of its unit tests, but I'm not able to use the weaver in a non netstandard project (eg. a console app with .net 4.6.1).

**Comment by AlexPalma72** [comment] 2017-09-12 09:00
that's strange could it be a Fody prb?

**Comment by csnemes** [comment] 2017-11-05 18:06
Managed to solve all issues. Just released version 2.0 which is now on netstandard 2.0.

**Closed by csnemes** 2017-11-05 18:06 UTC

**Comment by KevinYeti** [comment] 2018-01-12 07:10
@csnemes hi, I was tried to resolve the referencing problem in my own fody addins. can you share your solution to solve the problem ? 
I was considering using the ILMerge to solve but not work.

**Comment by csnemes** [comment] 2018-01-15 13:02
If you ask about the moving to netstandard 2.0 I had to upgrade to the latest VS2017 with the new project format. Also I replaced some functionality not present in the netstandard to something similar, like reading from environment variables instead of reading the app.config. Finally, I had to change some method calls as the signature I used was not part of the netstandard (e.g. adding some extra parameters to the call).

**Comment by KevinYeti** [comment] 2018-01-16 07:47
@csnemes 
hi, thank you for reply. 
I forked an addin from https://github.com/Dresel/MethodCache which was not updated for a long time. 
I'm now trying to port this addin to support .NET Standard2.0 
For now , my problem is very similar to this issue from you:
https://github.com/Fody/Fody/issues/378

I have already update fody to the latest version 2.3.20 and still got  the error of FileNotFoundException.

Fody: Could not load 'ModuleWeaver' from 'MethodCache.Fody, Version=1.0.18.0, Culture=neutral, PublicKeyToken=null' due to ReflectionTypeLoadException.
1>MSBUILD : error : It is possible the package needs to be updated.
1>MSBUILD : error : exception.LoaderExceptions:
1>MSBUILD : error : System.IO.FileNotFoundException: could not load assembly “netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”

 so I think maybe you have solve the problem.
